### ISSUE TITLE
最初に表示するデータを「放水」「機関戻り」の二つにしたい

### ISSUE THREAD

**Issue by fumi-k** [knaou/time-record#20]
チャートを開いたときに最初に表示するデータを「放水」「機関戻り」の二つにしたい。
あるいは，外付けで，最初に表示するデータを指定できるようにしたい。
優先度はだいぶ低め。

**Comment by knaou** [comment]
EntryTypeにデフォルトフラグを付ける。
フィルターされてない場合は、これを使うようにする
