### ISSUE TITLE
別の年のタイムデータを重ねて表示できるようにしたい

### ISSUE THREAD

**Issue by fumi-k** [knaou/time-record#30]
各年度ごとのデータを重ねて表示して，時間(回数)によるデータ変化の傾向を比較したい。

**Comment by knaou** [comment]
この手の比較はCSVで出力して、エクセルでグラフ化したほうがよい気がする。
それだと何か問題あるかな

**Comment by fumi-k** [comment]
方針に合わないから，難易度が高いから，工数が合わないから，といった理由でエンハンスしない選択肢はありだと思うよ。
でも，下記の意見は，「エクセルでグラフ化する方が良い」という理由が見えないので賛同できない。

> この手の比較はCSVで出力して、エクセルでグラフ化したほうがよい気がする。
> それだと何か問題あるかな

なぜエクセルの方が良い，と考えるのか意見を聞きたい。

**Comment by knaou** [comment]
```
方針に合わないから，難易度が高いから，工数が合わないから，といった理由でエンハンスしない
```

基本ここ。
データをサクッと入力して、それを最低限リアルタイムに共有するのがこのシステムのもともとの目的で、
多少ビューを頑張ってみたけど、これはまだ最低限の共有に必要の範疇かなと思ってる。

当然の要求として、これまでのデータと比較検討して、多方面から分析したい…は来るんだけど、
実はこのスコープを実現するのは、新規システムつくるくらい別種のシステムになってしまう。

必要あらば作るのも手だけど、そもそもみんなが知ってるツールに、「データを分析してグラフ描画できるツール」あったよね、ということでEXCEL推し。
ちな、使い手がいるなら、Pentahoもありかと思う。

**Comment by fumi-k** [comment]
この内容に合意します。クローズします。
