### ISSUE TITLE
あるデータの差分をプロットしたチャートを表示したい

### ISSUE THREAD

**Issue by fumi-k** [knaou/time-record#4]
入力したデータしか表示できていないが，データAとデータBの差分を表示したい。
現時点で具体的に表示したい差分値は，「放水」と「機関戻り」の差分。

**Comment by knaou** [comment]
Typeモデルは、ユーザによるデータ入力を前提としているけど、
これをちょっといじって、「差分」タイプを実装すれば行けるかもしれない。
