### ISSUE TITLE
データがない個所をスキップしてプロットしたい

### ISSUE THREAD

**Issue by fumi-k** [knaou/time-record#5]
データなしの箇所は"0"扱いでプロットされているため，チャートに不自然なスパイクができてしまう。
スパイクをなくしたチャートを表示したい。

**Comment by fumi-k** [comment]
修正版を確認したけど，自分のイメージとしては，チャートのプロット間は線が引かれている方が近かった。
ChartOptionsのspanGapsの値をtrueにしたチャートにしたいけど，できそうかな？
生成されるコードに以下のChartOptionsが入る感じ。

``` JS
    new Chart(ctx, {
      type: 'line',
      data: data,
      options: {
        spanGaps : true,
        pointDot : true,
        showTooltips: true
      }
    });
```

**Comment by knaou** [comment]
やってみる
