### ISSUE TITLE
ToolTipにメモを表示したい

### ISSUE THREAD

**Issue by fumi-k** [knaou/time-record#6]
ToolTipにメモを書けるようにしておくと，特別に早い，遅いといった要因をメモできて使いやすい。

**Comment by knaou** [comment]
ちょっと検討してみる。
Chart.js の　Tooltip のいじり方を調べておいてくれると助かる。
（ちな、1.x 系と 2.x 系でAPI変わってるので要注意。使ってるのは 2.x 系)

**Comment by fumi-k** [comment]
了解。Chart.js のTooltip のいじり方は調べておく。

**Comment by fumi-k** [comment]
こんなかんじでどうかな？
![default](https://cloud.githubusercontent.com/assets/22069193/18414686/dc79d362-780e-11e6-925a-97a4298b0e4c.png)

チャートのoptionsにtooltips.callbacksを追加。callbacksの記述はこんな感じ。
データは適当。マルチバイト使えるかとか長くなるとどうなるか，試すために変な文字列使ってるけど。そこは気にしないでほしい。
参考資料は以下のサイト。
http://www.chartjs.org/docs/#chart-configuration-tooltip-configuration
http://stackoverflow.com/questions/34720530/chart-js-v2-add-prefix-or-suffix-to-tooltip-label

```
    var memo = [
      "適当に文字列を入れたデータを使ってみた１",
      ...
      "適当に文字列を入れたデータを使ってみた。ここまで行くと流石に無茶だと思うが，とりあえずやってみることは重要だと思うが，さすがに無理ぽよ。"
    ];
    ...
      options: {
            tooltips: {
                enabled: true,
                mode: 'single',
                callbacks: {
                    afterLabel: function(tooltipItem, data) { 
                        return memo[tooltipItem.index];
                    }
                }
            },
        }
```

**Comment by fumi-k** [comment]
そもそもメモでやりたいことは以下の3つのうち，おそらく3。たとえば，ミスの内容，とかを記載するのが目的。
1. 各日付ごとにメモを表示する
2. 各Index毎にメモを表示する
3. 各データ毎にメモを表示する

3を実現するとしたら，各値データに関連させた文字列データを保持する必要が出てくる。
2での実現ならば，DataTypeにグラフに表示しない文字列型を定義して，関連付けをやる，とかで実現できそうだから，もう少し楽に見える。
