### ISSUE TITLE
チャートの目盛り幅を任意の値に選択したい

### ISSUE THREAD

**Issue by fumi-k** [knaou/time-record#9]
チャートの目盛り幅の値は自動的に決定されるが，「5」のような大きい値になることがある。
より詳細に差分を確認する場合，目盛り幅を「1」などの小さい値にしてチャートを確認したい。

**Comment by knaou** [comment]
なるほど。　From ~ To と、間隔ね。

**Comment by knaou** [comment]
https://github.com/knaou/time-record/issues/3
で解決
